DROP TABLE IF EXISTS `users` CASCADE;
DROP TABLE IF EXISTS `friends` CASCADE;
DROP TABLE IF EXISTS `films` CASCADE;
DROP TABLE IF EXISTS `genre` CASCADE;
DROP TABLE IF EXISTS `mpa` CASCADE;
DROP TABLE IF EXISTS `likes` CASCADE;
DROP TABLE IF EXISTS `films_genre` CASCADE;


CREATE TABLE IF NOT EXISTS "users" (
                         "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "EMAIL" varchar,
                         "login" varchar,
                         "name" varchar,
                         "birthday" date
);

CREATE TABLE IF NOT EXISTS "friends" (
                           "user_id" bigint,
                           "friends_id" integer,
                           "confirmation_friendship" boolean
);

CREATE TABLE IF NOT EXISTS "films" (
                         "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "name" varchar,
                         "description" varchar,
                         "releaseDate" date,
                         "mpa_id" integer,
                         "duration" integer
);

CREATE TABLE IF NOT EXISTS "genre" (
                         "genre_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "name" varchar
);

CREATE TABLE IF NOT EXISTS "mpa" (
                       "mpa_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       "name" varchar
);

CREATE TABLE IF NOT EXISTS "likes" (
                         "user_id" bigint,
                         "film_id" bigint
);

CREATE TABLE IF NOT EXISTS "films_genre" (
                               "films_id" bigint,
                               "genre_id" int
);

ALTER TABLE "friends" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "friends" ADD FOREIGN KEY ("friends_id") REFERENCES "users" ("id");

ALTER TABLE "films" ADD FOREIGN KEY ("mpa_id") REFERENCES "mpa" ("mpa_id");

ALTER TABLE "likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "likes" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("id");

ALTER TABLE "films_genre" ADD FOREIGN KEY ("films_id") REFERENCES "films" ("id");

ALTER TABLE "films_genre" ADD FOREIGN KEY ("genre_id") REFERENCES "genre" ("genre_id");